export RISING_MAINTAINER=DjancoX
export RISING_PACKAGE_TYPE=VANILLA_AOSP
export USE_NOTES=true
export USE_VOICE_RECORDER=true
export TARGET_USE_DOLBY=true
export USE_LATINIME=true
export USE_CHROMITE=true
